<Project ToolsVersion="12.0" DefaultTargets="PostBuildEvent" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="ILMerge" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <InputAssemblies Include="$(OutputPath)Vim.Format.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.Format.Core.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.BFast.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.G3d.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.LinqArray.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.Math3D.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.Util.dll" />
            <InputAssemblies Include="$(OutputPath)Vim.Util.Logging.Serilog.dll" />
            <InputAssemblies Include="$(OutputPath)Serilog.dll" />
            <InputAssemblies Include="$(OutputPath)Serilog.Sinks.Console.dll" />
            <InputAssemblies Include="$(OutputPath)Serilog.Sinks.EventLog.dll" />
            <InputAssemblies Include="$(OutputPath)Serilog.Sinks.File.dll" />
            <InputAssemblies Include="$(OutputPath)Serilog.Sinks.RollingFile.dll" />
        </ItemGroup>
        <ILRepack
            Parallel="true"
            TargetPlatformVersion="v4"
            TargetKind="Dll"
            InputAssemblies="@(InputAssemblies)"
            OutputFile="$(OutputPath)/Vim.Format.Standalone.dll"
        />
        <!--<Exec Command='$(ILRepack) ^
      /parallel ^
      /targetplatform:v4 ^
      /out: ^
      $(OutputPath)Vim.Format.dll ^
      $(OutputPath)Vim.Format.Core.dll ^
      $(OutputPath)Vim.BFast.dll ^
      $(OutputPath)Vim.G3d.dll ^
      $(OutputPath)Vim.LinqArray.dll ^
      $(OutputPath)Vim.Math3D.dll ^
      $(OutputPath)Vim.Util.dll ^
      $(OutputPath)Vim.Util.Logging.Serilog.dll ^
      $(OutputPath)Serilog.dll ^
      $(OutputPath)Serilog.Sinks.Console.dll ^
      $(OutputPath)Serilog.Sinks.EventLog.dll ^
      $(OutputPath)Serilog.Sinks.File.dll ^
      $(OutputPath)Serilog.Sinks.RollingFile.dll' />-->
    </Target>

</Project>
