<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageProjectUrl>https://github.com/vimaec/vim-format</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vimaec/vim-format</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.8.3</Version>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CommonAssemblyInfoVersion)' != ''">
    <!-- version override when built from parent repo -->
    <Version>$(CommonAssemblyInfoVersion)</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RepoNugetOutputDir)' != ''">
    <!-- output directory override when built from parent repo -->
    <PackageOutputPath>$(RepoNugetOutputDir)</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vim.Util\Vim.Util.csproj" />
  </ItemGroup>

</Project>
