<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Vim.Util</RootNamespace>
    <PackageProjectUrl>https://github.com/vimaec/vim-format</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vimaec/vim-format</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.8.3</Version>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CommonAssemblyInfoVersion)' != ''">
    <!-- version override when built from parent repo -->
    <Version>$(CommonAssemblyInfoVersion)</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RepoNugetOutputDir)' != ''">
    <!-- output directory override when built from parent repo -->
    <PackageOutputPath>$(RepoNugetOutputDir)</PackageOutputPath>
  </PropertyGroup>
</Project>
